# Configuration file for Rustfmt
# https://rust-lang.github.io/rustfmt

version = "Two"

# Basic
hard_tabs = true
max_width = 100

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Consistency
newline_style = "Unix"

# Format comments
comment_width = 100
wrap_comments = true

# Misc
chain_width = 80
match_arm_blocks = false
match_block_trailing_comma = true
reorder_impl_items = true
trailing_semicolon = true
use_field_init_shorthand = true

# Ignore generated files
ignore = [
  "backend/common/infrastructure/src/database/schema.rs",
]
