[package]
description = "testing utils (setupd, contexts, fixtures, mocks)"
edition = "2021"
license-file = "LICENSE"
name = "testing"
version = "0.1.0"

[lib]

[dependencies]

# Async
tokio = { version = "1.18.2", features = ["full"] }

# Local dependecies
anyhow = "1.0.57"
lapin = "2.3.1"
testcontainers = "0.14.0"
tokio-async-drop = "0.1.0"
project-root = "0.2.2"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive"] }

domain = { path = "../domain" }
infrastructure = { path = "../infrastructure" }
