name: Chromatic

on:
#  pull_request: ~

  push:
    branches:
      - "main"
      - "hotfix/**"

env:
  VITE_CLOUDFLARE_RESIZE_W_100_PREFIX: https://onlydust.xyz/cdn-cgi/image/width=100/

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest-4-cores
    env:
      TS_NODE_IGNORE: "*"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn frontend:install
        # ðŸ‘‡ Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          # ðŸ‘‡ Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: frontend

