name: E2E tests

on:
  pull_request: ~

  push:
    branches:
      - "main"
      - "hotfix/**"

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

env:
  GITHUB_PAT: ${{ secrets.CI_GITHUB_TOKEN }}
  DUSTY_BOT_GITHUB_PAT: ${{ secrets.CI_GITHUB_TOKEN }}
  GITHUB_PAT_FOR_E2E_TESTS_USERS: ${{ secrets.CI_GITHUB_PAT_FOR_E2E_TESTS_USERS }}
  HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256","key":"5152fa850c02dc222631cca898ed1485821a70912a6e3649c49076912daa3b62182ba013315915d64f40cddfbb8b58eb5bd11ba225336a6af45bbae07ca873f3","issuer":"hasura-auth"}'
  HASURA_GRAPHQL_EXPERIMENTAL_FEATURES: naming_convention
  HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: graphql-default
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  PROFILE: local
  GITHUB_MAX_CALLS_PER_REQUEST: 100
  DUSTY_BOT_GITHUB_MAX_CALLS_PER_REQUEST: 100
  BACKEND_GRAPHQL_API_KEY: myapikey
  GITHUB_PROXY_GRAPHQL_API_KEY: mygithubproxyapikey
  DUSTY_BOT_GITHUB_BASE_URL: https://api.github.com/
  GITHUB_BASE_URL: https://api.github.com/

jobs:
  e2e_tests:
    name: End-to-end tests
    runs-on: ubuntu-latest-16-cores

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare env
        run: git config --global --add safe.directory /app

      - name: Copy the .env file
        shell: bash
        run: cp .env.e2e .env

      - name: Start the docker stack
        run: yarn e2e:env:up

      - name: Prepare Hasura
        run: |
          yarn hasura:console:install
          yarn e2e:hasura:delete-metadata
          yarn hasura:metadata:apply
          yarn hasura:metadata:drop-inconsistencies
          yarn hasura:export

      - name: Check database and GraphQL schema consistency
        run: yarn hasura:metadata:check-consistency

      - name: Dump docker logs on failure
        if: ${{ failure() }}
        uses: jwalton/gh-docker-logs@v2

      - name: Log inconsistencies list on failure
        if: ${{ failure() }}
        run: yarn hasura:metadata:log-inconsistencies

      - name: Install Playwright
        run: yarn e2e:install

      - name: Run the end-to-end tests
        run: yarn e2e:run

      - name: Setup tmate session for debugging
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() && inputs.debug_enabled }}

      - name: Upload screenshots in case of failure
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: playwright-report
          path: e2e/playwright/playwright-report/
          retention-days: 7

      - name: Upload DB dump in case of failure
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: playwright-db-dump
          path: e2e/playwright/marketplace_db_dump
          retention-days: 7
